### PR TITLE
Bug fix: link for packages don't work after input something for search

### PR DESCRIPTION
**Pull request by vitaliy-orlov**
Hi!

How to reproduce a bug:
1. Input something to search component
2. Click on package

## Expected Behavior

View package detailed information

## Actual Behavior

Nothing happens. Only changed url in browser.

### CODE REVIEW

**Comment by loic-sharma** [comment]
Good catch! Won’t your changes break the search bar on the “Upload” page? I’ll merge this in next week when I’m back from the holidays. Thanks!

**Comment by vitaliy-orlov** [comment]
I think not, but just in case, I'll check.

**Comment by loic-sharma** [comment]
Hey, I solved this using a different approach here: https://github.com/loic-sharma/BaGet/pull/186

I hooked into React Router's history and wiped `App.state.input` whenever the route changes. This seems to work really well. Please let me know what you think!

**Comment by loic-sharma** [comment]
Closing this as the other fix has been merged. Thanks for reporting this @vitaliy-orlov! :)

**Comment by vitaliy-orlov** [comment]
@loic-sharma you're welcome! But i found new issues. I'm not exactly sure, but they may be related to the current change.

First one (actions): 
1. input something to search
2. click link 'upload'
3. click link 'search'

**Expected Behavior** - search input have to be cleared or search have to apply filter. Or u can look at nuhet.org behavior.

**Actual Behavior** - search input had the data and filter did not apply

Second one (actions):
1. click to any package to see details
2. click link 'search'

**Expected Behavior** - browser url changed from /packages/:id to /packages

**Actual Behavior** - browser url did not changed

**Pull request closed without merging**
