### PR TITLE
Create pushing_packages.md

### PR DESCRIPTION
**Pull request by akovac35**
Added a more elaborate example on how to push packages.

### CODE REVIEW

**Comment by loic-sharma** [comment]
Hi, thanks for opening this pull request. I'm concerned that this script is a little too specific for most users. The `*` wildcard feature on `dotnet nuget push` is probably enough for most people. What are your thoughts?

**Comment by akovac35** [comment]
> Hi, thanks for opening this pull request. I'm concerned that this script is a little too specific for most users. The `*` wildcard feature on `dotnet nuget push` is probably enough for most people. What are your thoughts?

Well the snippet is definitively useful because it deals in one place with many of the typical problems encountered when pushing nugets:

- detect a test has failed,
- clean, build, pack "Release" variants of all solution projects,
- find the above and push to BaGet,
- configuration steps for uploading nugets when the repository is protected with a key,
- just gives a general idea and a starting point for many common nuget related matters, such as how to skip packing a project and creating and pushing symbol packages which is typically an afterthought.

```dotnet nuget push``` definitively does not cut it most of the time, or I would not go through the hassle. For example, it might push debug variants if we are not careful, then there is the hassle with the key, which you have to find online, and just don't get me started on the star *, I wasn't even aware it exists.

To conclude, BaGet will get loads more stars just because of this script ;)

**Comment by loic-sharma** [comment]
Your script is definitely useful, but I don't think it's a good fit for BaGet's documentation. I'd prefer to document the basics geared towards beginners. For example, how do I upload my first package? How do I import packages from some other server? How do I use MySQL?

Your script is more for advanced users that are looking for best practices. This would make for a great blog post though!

**Comment by akovac35** [comment]
I will make a gist instead.

**Pull request closed without merging**
