### PR TITLE
Adds .NET 6.0, .NET 7.0, .NET 8.0, and .NET Framework 4.8.1 to TargetFrameworks

### PR DESCRIPTION
**Pull request by joestr**
Adds additional frameworks for searching

 * .NET 7.0 (`net7.0`)
 * .NET 6.0 (`net6.0`)
 * .NET Framework 4.8.1 (`net481`)

Addresses https://github.com/loic-sharma/BaGet/issues/750

### CODE REVIEW

**Comment by david-m77** [comment]
Can you also add net8.0. Thanks

**Comment by seriouz** [comment]
Your commits are merged into the new BaGetter fork https://github.com/bagetter/BaGetter

**Comment by joestr** [comment]
> Your commits are merged into the new BaGetter fork https://github.com/bagetter/BaGetter

Yeah already checked that out and replaced my production instance with it. 👌

**Comment by RegexCore** [comment]
Can you also update docker image "loicsharma/baget" regarding this added frameworks? (Docker image is really old - Updated over 2 years ago)

Thank You!

**Comment by seriouz** [comment]
@MagicFawkes have a look at [BaGetter](https://github.com/bagetter/BaGetter?tab=readme-ov-file#bagetter-).

**Comment by RegexCore** [comment]
> @MagicFawkes have a look at [BaGetter](https://github.com/bagetter/BaGetter?tab=readme-ov-file#bagetter-).

Thank you for this link :-), there is an old image on the website I used before

**Pull request closed without merging**
