### PR TITLE
Fix to string truncation error for packages with >4000 char release notes 

### PR DESCRIPTION
**Pull request by dncnkrs**
Summary of the changes (in less than 80 chars)

 * Fixed mismatching column length between database and nuspec

Addresses https://github.com/loic-sharma/BaGet/issues/609

## Issue details

I had this problem with Hangfire, exactly the same package as in #609.

The issue is caused by Hangfire having 6700 character release notes, while BaGet only allocates 4000 character columns for this field. 

The nuspec file reference allows up to 35000 characters in the release notes field: https://docs.microsoft.com/en-us/nuget/reference/nuspec#releasenotes.

To fix this, I've amended the max length of this field to 35000. 

## Caveats etc

I'm no fan of ef migrations, so double check my work here.

### CODE REVIEW

**Comment by Svisstack** [comment]
Can we release this after the merge request, so we will be able to ingest that change through entity framework migration after the new baget container startup?

**Comment by viceice** [comment]
closes #590

**Comment by EdmondFrank** [comment]
Good job ! I encountered the same problem. Before that, I only temporarily solved the problem through altering the table field by following statement. 
```sql
ALTER TABLE "Packages" ALTER COLUMN "ReleaseNotes" TYPE text;
```

**Comment by Svisstack** [comment]
Why it’s not permanent?

**Comment by EdmondFrank** [comment]
> Why it’s not permanent?
> […](#)
> Sent from my iPhone
> On 6 May 2021, at 08:56, edmonfrank ***@***.***> wrote: ﻿ Good job ! I encountered the same problem. Before that, I only temporarily solved the problem through altering the table field by following statement. ALTER TABLE "Packages" ALTER COLUMN "ReleaseNotes" TYPE text; — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe.

What I want to express is that when you need deploy the project from zero, this problem still exists. You need manually alter the table again.

**Review by splawless — APPROVED** [review]
[](https://github.com/loic-sharma/BaGet/pull/610/files)**_[](https://github.com/loic-sharma/BaGet/pull/610/files)_**

**Comment by loic-sharma** [comment]
Hi @dncnkrs, I apologize for taking so long to review this. I ended up removing the release notes limit in https://github.com/loic-sharma/BaGet/pull/687 as nuget.org has a few packages whose release notes are over 400K! Thanks for your help!

**Pull request closed without merging**
