### PR TITLE
Make it possible to configure the API key without hashing.

### PR DESCRIPTION
**Pull request by tmds**
Passing passwords unhashed is a common technique in containers.
Such passwords are stored and shared in the container platform.

### CODE REVIEW

**Comment by loic-sharma** [comment]
What do you think of removing the `ApiKeyHash` config altogether? ASP.NET has a pretty good story around secrets in configurations, so hashing should be unnecessary.

**Comment by tmds** [comment]
If no one has requested it, I think it we can remove it.
You can add it back if someone has a strong case for it.
Do you want me to remove it? That will be a breaking change.

**Comment by LordMike** [comment]
Does nugets protocol for API Keys seriously just hash the API key?

It provides nothing over just sending the API key as is - it's the same shared secret... :|

**Comment by loic-sharma** [comment]
@LordMike NuGet sends the API key in plaintext over HTTPS, but stores hashes of the API key in the database. You can think of an API key like a username and password credential.

**Comment by LordMike** [comment]
Oh good. Hashing it brings nothing to the transport. :P

**Comment by loic-sharma** [comment]
Thanks @tmds!

**Pull request merged**
