### PR TITLE
Fix docker build

### PR DESCRIPTION
**Pull request by Mizipzor**
### What does this PR do?

Fix docker build.

### Closes Issue(s)

#129

### Motivation

Need to be able to build docker image locally to make changes.

### CODE REVIEW

**Comment by daniel-lerch** [comment]
I can confirm that the docker build works with this fix. However the SPA middleware is not able to find `index.html` and I get an error page no matter whether I run in development or production environment:

---
An unhandled exception occurred while processing the request.
AggregateException: One or more errors occurred. (One or more errors occurred. (Failed to start 'npm'. To resolve this:.

[1] Ensure that 'npm' is installed and can be found in one of the PATH directories.
Current PATH enviroment variable is: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Make sure the executable is in one of those directories, or update your PATH.

[2] See the InnerException for further details of the cause.))
System.Threading.Tasks.Task<TResult>.GetResultCore(bool waitCompletionNotification)

InvalidOperationException: Failed to start 'npm'. To resolve this:.

[1] Ensure that 'npm' is installed and can be found in one of the PATH directories.
Current PATH enviroment variable is: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
Make sure the executable is in one of those directories, or update your PATH.

[2] See the InnerException for further details of the cause.
Microsoft.AspNetCore.NodeServices.Npm.NpmScriptRunner.LaunchNodeProcess(ProcessStartInfo startInfo)

**Comment by Mizipzor** [comment]
Hm, so did I install npm in a bad way then?

**Comment by daniel-lerch** [comment]
There are actually two different errors. Sorry for mixing them up.

1. BaGet uses `npm` when running in a development environment ([code](https://github.com/loic-sharma/BaGet/blob/b264b93ec2a0a8a73692c1ed9749bf9541c2aa59/src/BaGet/Startup.cs#L78)). You installed `npm` only in the build container what is absolutely right. Microsoft strongly discourages people from using this function in production.
2. In production the SPA middleware does not find the static content files although it seems to be configured correctly. I'm currently investigating why.

**Comment by daniel-lerch** [comment]
On Windows it works, but not on Linux/Docker. The problem is again the case sensitive folder name `BaGet.UI` (see [here](https://github.com/loic-sharma/BaGet/blob/b264b93ec2a0a8a73692c1ed9749bf9541c2aa59/src/BaGet/Startup.cs#L31)).
As I don't have access to amend your pull request I would ask you to change the root path in the linked code line from `Baget.UI/build` to `BaGet.UI/build`.

**Comment by loic-sharma** [comment]
@diman84 opened up a pull request that also covers the issues @daniel-lerch mentioned: https://github.com/loic-sharma/BaGet/pull/132

I went ahead and merged that PR instead. Thank you for the good work @Mizipzor! Please let me know if y'all run into any additional issues

**Pull request closed without merging**
