### PR TITLE
Allow overriding PackageService methods

### PR DESCRIPTION
**Pull request by ismcagdas**
Allow overriding PackageService methods so that a new package service like MyPackageService can be inherited from PackageService instead of implementing IPackageService fully.

### CODE REVIEW

**Comment by loic-sharma** [comment]
Thanks for opening this pull request! How’re you customizing `PackageService`? I’d like to better understand your scenario better before comitting to a solution.

**Comment by ismcagdas** [comment]
@loic-sharma sure, for now I implement `IPackageService` something like below:

```
public class MyPackageService : IPackageService
{
    // implementation
}
```

Instead of implementing the entire interface, I would like to use it like below:

```
public class MyPackageService : PackageService
{
    public override async Task<IReadOnlyList<Package>> FindAsync(string id, bool includeUnlisted = false)
    {
        // My custom implementation
    }
}
```

Then, use MyPackageService like below:

`services.AddTransient<IPackageService, MyPackageService>();`

**Comment by loic-sharma** [comment]
Could you instead do something like:

```csharp
public class MyPackageService : IPackageService
{
    private readonly PackageService _defaultPackageService;

    public MyPackageService(PackageService defaultPackageService)
    {
        _defaultPackageService = defaultPackageService ?? throw new ArgumentNullException(nameof(defaultPackageService));
    }

    public Task<PackageAddResult> AddAsync(Package package) => _defaultPackageService.AddAsync(package);
    public Task<bool> Exists(string id, NuGetVersion version = null) => _defaultPackageService.Exists(id, version);

    // ...

    public override async Task<IReadOnlyList<Package>> FindAsync(string id, bool includeUnlisted = false)
    {
        // My custom implementation
    }
}
```

You'll need to tweak the dependency injection a little:

```csharp
services.AddTransient<PackageService>();
services.AddTransient<IPackageService, MyPackageService>();
```

I acknowledge that this isn't as convenient as overriding methods, however, I'd prefer this over setting a precedent of virtual methods for extensibility. Let me know what you think!

**Comment by ismcagdas** [comment]
@loic-sharma no problem, I will use it like that, thank you.

**Comment by loic-sharma** [comment]
Please let me know if you run into any issues or have any additional feedback. Cheers!

**Pull request closed without merging**
