### PR TITLE
Two additional ways of access in AWS S3

### PR DESCRIPTION
**Pull request by richarddowner**
Summary of the changes (in less than 80 chars)

 * Added UseInstanceProfile config option, for using fallback credentials (instance profile) in AWS
 * Added AssumeRoleArn config option, for assuming cross account role in AWS
 * Todo: Update documentation, not sure where to do this?

Addresses https://github.com/loic-sharma/BaGet/issues/266

### CODE REVIEW

**Comment by loic-sharma** [comment]
Thank you for doing this work, this looks great! I'll send a pull request to update the documentation, and I'll tag you on it so that you can review it.

**Comment by altso** [comment]
@richarddowner @loic-sharma I just tried to use in `AssumeRoleArn` and got this exception:

```
System.InvalidOperationException: Assembly AWSSDK.SecurityToken could not be found or loaded.
This assembly must be available at runtime to use Amazon.Runtime.AssumeRoleAWSCredentials.
```

It looks similar to https://github.com/aws/aws-lambda-dotnet/issues/223 and the resolution there was to add `AWSSDK.SecurityToken` as a dependency.

I can create a pull request with this change if you think it's the way to go.

**Comment by loic-sharma** [comment]
@altso Thanks for reporting this! Your fix sounds good to me, I'd be happy to accept a pull request :)

**Comment by altso** [comment]
@loic-sharma created #460

**Pull request merged**
